server:
  port: 8766

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka  ## 注册到 eureka
spring:
  application:
    name: consumer-server-service  ## 应用程序名称，后面会在消费者中用到

#config swagger
swagger:
  enabled: true
